using Application.Abstractions.Services;
using Application.Common.Pdf;
using QuestPDF.Fluent;
using QuestPDF.Helpers;


namespace Infrastructure.Pdf;

public sealed class OrderPdfGenerator : IOrderPdfGenerator
{
    public byte[] Generate(OrderPdfData data)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Column(column =>
                {
                    column.Item().Row(row =>
                    {
                        row.RelativeItem().Column(col =>
                        {
                            col.Item().Text(data.TenantName).FontSize(16).Bold();
                            col.Item().Text($"PIB: {data.TenantPib}");
                            col.Item().Text(data.TenantAddress);
                        });

                        row.ConstantItem(160).Column(col =>
                        {
                            col.Item().AlignRight().Text("PURCHASE ORDER").FontSize(14).Bold();
                            col.Item().AlignRight().Text($"Order #{data.OrderPublicId[..8].ToUpper()}");
                            col.Item().AlignRight().Text(data.OrderDate.ToString("dd MMM yyyy"));
                        });
                    });

                    column.Item().PaddingTop(10).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                });

                page.Content().PaddingVertical(20).Column(column =>
                {
                    column.Spacing(15);

                    column.Item().Column(col =>
                    {
                        col.Item().Text("Supplier").Bold().FontSize(11);
                        col.Item().Text(data.SupplierName);
                        if (!string.IsNullOrWhiteSpace(data.SupplierContactEmail))
                            col.Item().Text(data.SupplierContactEmail);
                        if (!string.IsNullOrWhiteSpace(data.SupplierContactPhone))
                            col.Item().Text(data.SupplierContactPhone);
                    });

                    column.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(4);
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(2);
                            columns.RelativeColumn(2);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("Product").Bold();
                            header.Cell().AlignRight().Text("Qty").Bold();
                            header.Cell().AlignRight().Text("Unit Price").Bold();
                            header.Cell().AlignRight().Text("Total").Bold();

                            header.Cell().ColumnSpan(4).PaddingTop(5).BorderBottom(1).BorderColor(Colors.Grey.Lighten1);
                        });

                        foreach (var item in data.Items)
                        {
                            table.Cell().PaddingVertical(4).Text(item.ProductName);
                            table.Cell().PaddingVertical(4).AlignRight().Text(item.Quantity.ToString());
                            table.Cell().PaddingVertical(4).AlignRight().Text($"{item.UnitPrice:N2}");
                            table.Cell().PaddingVertical(4).AlignRight().Text($"{item.Total:N2}");
                        }
                    });

                    var grandTotal = data.Items.Sum(i => i.Total);

                    column.Item().AlignRight().PaddingTop(10).Text($"Total: {grandTotal:N2}").FontSize(13).Bold();
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by StockSense").FontSize(8).FontColor(Colors.Grey.Medium);
                });
            });
        });

        return document.GeneratePdf();
    }
}
